"""
Writes a collected configuration dict to a clean, annotated SU2 .cfg file.
"""

import textwrap
from datetime import date
from su2wizard.db import OptionsDB


def write_cfg(config: dict, db: OptionsDB, output_path: str,
              case_name: str = "", author: str = "") -> None:
    """
    Write config dict to output_path as a well-formatted .cfg file.

    Each option is preceded by a short comment with its description.
    Options are grouped by wizard stage section.
    """
    today = date.today().isoformat()
    header = f"""\
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                              %
% SU2 configuration file                                                       %
% Case description: {case_name:<54} %
% Author: {author:<63} %
% Date: {today:<66} %
% Generated by su2-wizard (based on SU2 v{db.version})                        %
%                                                                              %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

"""

    # Build a lookup: option_name → stage label
    stage_map: dict[str, str] = {}
    for stage_label, keys in db.wizard_stages:
        for k in keys:
            stage_map[k] = stage_label

    # Group config keys by stage (preserve stage order)
    stage_order = [label for label, _ in db.wizard_stages]
    staged: dict[str, list[str]] = {label: [] for label in stage_order}
    ungrouped: list[str] = []
    for key in config:
        label = stage_map.get(key)
        if label:
            staged[label].append(key)
        else:
            ungrouped.append(key)

    lines = [header]

    def _write_option(key: str) -> str:
        val = config[key]
        desc = db.description(key)
        choices = db.choices(key)
        block = []
        block.append("%")
        if desc:
            for l in textwrap.wrap(desc, width=76):
                block.append(f"% {l}")
        if choices:
            choice_str = ", ".join(choices)
            for l in textwrap.wrap(f"Options: {choice_str}", width=76):
                block.append(f"% {l}")
        block.append(f"{key}= {val}")
        block.append("%")
        return "\n".join(block)

    for stage_label in stage_order:
        keys_in_stage = staged.get(stage_label, [])
        keys_in_stage_in_config = [k for k in keys_in_stage if k in config]
        if not keys_in_stage_in_config:
            continue
        sep = "%" + "-" * 77 + "%"
        lines.append(sep)
        lines.append(f"% {stage_label.upper():^76}%")
        lines.append(sep)
        lines.append("")
        for key in keys_in_stage_in_config:
            lines.append(_write_option(key))
            lines.append("")

    if ungrouped:
        lines.append("%" + "-" * 77 + "%")
        lines.append("% ADDITIONAL OPTIONS" + " " * 57 + "%")
        lines.append("%" + "-" * 77 + "%")
        lines.append("")
        for key in ungrouped:
            lines.append(_write_option(key))
            lines.append("")

    content = "\n".join(lines)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
